dist: trusty
language: perl
perl:
- "5.10"
- "5.28"
install:
- cpanm Perl::MinimumVersion
- cpanm Perl::Critic
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- make -C doc/
- make -C doc/ check
- private/run-perlcritic
- make test
- make install PREFIX=~/.local
- cd /
- localehelper --help
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 localehelper | grep -A 10 -w LOCALEHELPER

# vim:ts=2 sts=2 sw=2 et
