dist: trusty
sudo: false
language: perl
perl:
- "5.10"
- "5.24"
install:
- cpanm Perl::MinimumVersion
- cpanm Perl::Critic
script:
- make -C doc/
- private/run-perlcritic
- make test
- make install PREFIX=~/.local
- export PATH=~/.local/bin:"$PATH"
- localehelper --help
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 localehelper | grep -A 10 -w LOCALEHELPER

# vim:ts=2 sts=2 sw=2 et
