name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-22.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: APT install deps
      run: sudo apt-get install
        libperl-critic-perl
        libperl-minimumversion-perl
    - name: pip install deps
      run: |
        python3 -m pip install docutils pygments
    - name: build docs
      run: |
        make -C doc/
    - name: check docs
      run: |
        make -C doc/ check
    - name: check Perl version
      run: |
        perl --version
    - name: run perlcritic
      run: |
        private/run-perlcritic
    - name: run tests
      run: |
        make test
    - name: install
      run: |
        make install PREFIX=~/.local
    - name: run post-install tests
      run: |
        rm localehelper
        make test-installed
        git restore localehelper
        cd /
        localehelper --help
        export MANPATH=~/.local/share/man MANWIDTH=80
        man 1 localehelper | grep -A 10 -w LOCALEHELPER

# vim:ts=2 sts=2 sw=2 et
